apiVersion: batch/v1
kind: CronJob 
metadata:
  name: gazelle-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: gazelle 
            image: charlesdalton/gazelle:latest
            env:
            - name: GAZELLE_TELEGRAM_TOKEN
              value: ${GAZELLE_TELEGRAM_TOKEN}
            - name: INFURA_API_KEY
              value: ${INFURA_API_KEY}
