apiVersion: batch/v1
kind: CronJob 
metadata:
  name: gazelle-job
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: gazelle 
            image: charlesdalton/gazelle:latest
            env:
            - name: GAZELLE_TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gazelle-secret
                  key: GAZELLE_TELEGRAM_TOKEN
            - name: INFURA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gazelle-secret
                  key: INFURA_API_KEY
